import { Poppins } from "next/font/google";
import { Geist_Mono } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/sih.png"
  },
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${poppins.variable} ${geistMono.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-poppins), Arial, Helvetica, sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
